apiVersion: v1
kind: Service
metadata:
  name: orders-service
spec:
  clusterIP: 172.20.1.30
  selector:
    app: orders-app
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-app
  
spec:
  selector:
    matchLabels:
      app: orders-app
  replicas: 1
  template:
    metadata:
      labels:
        app: orders-app
    spec:
      containers:
      - name: orders-app
        image: ignaciomontero2022/orders-service-example
        env:
         - name: APP_ARGS
           value: "http://172.20.1.10 http://172.20.1.20 http://172.20.1.40"
        resources:
          requests:
            memory: "500Mi"
            cpu: "250m"
          limits:
            memory: "1000Mi"
            cpu: "500m"
        
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080